//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaChamCong { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime NgayChamCong { get; set; }
        public Nullable<int> SoNgayLam { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
