//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public int MaLuong { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime ThangNam { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public decimal Luong1 { get; set; }
        public string GhiChu { get; set; }
        public decimal LuongCoBan { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
